/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sonudoo_AccountKeeper_Cipher */

#ifndef _Included_com_sonudoo_AccountKeeper_Cipher
#define _Included_com_sonudoo_AccountKeeper_Cipher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sonudoo_AccountKeeper_Cipher
 * Method:    encrypt
 * Signature: (I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_sonudoo_AccountKeeper_Cipher_encrypt
        (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     com_sonudoo_AccountKeeper_Cipher
 * Method:    decrypt
 * Signature: (I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_sonudoo_AccountKeeper_Cipher_decrypt
        (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
